=== EvseevDA/funeral-service-jaxb-demo/dataBase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- UTIL TYPES -->
    <!-- Bounded string -->
    <xs:simpleType name="boundedString">
        <xs:restriction base="xs:string">
            <xs:minLength value="0"></xs:minLength>
            <xs:maxLength value="255"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>

    <!-- Price -->
    <xs:simpleType name="price">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0.01"></xs:minInclusive>
        </xs:restriction>
    </xs:simpleType>

    <!-- Positive count -->
    <xs:simpleType name="positiveCount">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1"></xs:minInclusive>
        </xs:restriction>
    </xs:simpleType>

    <!-- Percent discount -->
    <xs:simpleType name="percentDiscount">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"></xs:minInclusive>
            <xs:maxInclusive value="100"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>

    <!-- OBJECT TYPES -->
    <!-- Client -->
    <xs:complexType name="client">
        <xs:sequence>
            <xs:element name="surname" type="boundedString"></xs:element>
            <xs:element name="name" type="boundedString"></xs:element>
            <xs:element name="patronymic" type="boundedString"></xs:element>
            <xs:element name="country" type="boundedString"></xs:element>
            <xs:element name="region" type="boundedString"></xs:element>
            <xs:element name="city" type="boundedString"></xs:element>
            <xs:element name="phoneNumber" type="boundedString"></xs:element>
            <xs:element name="index" type="boundedString"></xs:element>
        </xs:sequence>
        <xs:attribute name="clientId" type="xs:int" use="required"></xs:attribute>
    </xs:complexType>

    <!-- Employee -->
    <xs:complexType name="employee">
        <xs:sequence>
            <xs:element name="surname" type="boundedString"></xs:element>
            <xs:element name="name" type="boundedString"></xs:element>
            <xs:element name="patronymic" type="boundedString"></xs:element>
            <xs:element name="jobTitle" type="boundedString"></xs:element>
            <xs:element name="birthday" type="xs:date"></xs:element>
            <xs:element name="hireDate" type="xs:date"></xs:element>
            <xs:element name="country" type="boundedString"></xs:element>
            <xs:element name="region" type="boundedString"></xs:element>
            <xs:element name="city" type="boundedString"></xs:element>
            <xs:element name="district" type="boundedString"></xs:element>
            <xs:element name="street" type="boundedString"></xs:element>
            <xs:element name="houseNumber" type="boundedString"></xs:element>
            <xs:element name="apartamentNumber" type="boundedString"></xs:element>
            <xs:element name="phoneNumber" type="boundedString"></xs:element>
            <xs:element name="photoUrl" type="boundedString"></xs:element>
            <xs:element name="note" type="boundedString"></xs:element>
            <xs:element name="reportsTo" type="boundedString"></xs:element>
        </xs:sequence>
        <xs:attribute name="employeeId" type="xs:int" use="required"></xs:attribute>
    </xs:complexType>

    <!-- Employee in order -->
    <xs:complexType name="employeeInOrder">
        <xs:sequence>
            <xs:element ref="employee"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Employees in order -->
    <xs:complexType name="employeesInOrder">
        <xs:sequence>
            <xs:element ref="employeeInOrder" minOccurs="1" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Provider -->
    <xs:complexType name="provider">
        <xs:sequence>
            <xs:element name="name" type="boundedString"></xs:element>
            <xs:element name="speakTo" type="boundedString"></xs:element>
            <xs:element name="jobTitle" type="boundedString"></xs:element>
            <xs:element name="country" type="boundedString"></xs:element>
            <xs:element name="region" type="boundedString"></xs:element>
            <xs:element name="city" type="boundedString"></xs:element>
            <xs:element name="index" type="boundedString"></xs:element>
            <xs:element name="phoneNumber" type="boundedString"></xs:element>
        </xs:sequence>
        <xs:attribute name="providerId" type="xs:int" use="required"></xs:attribute>
    </xs:complexType>

    <!-- Affilation type -->
    <xs:complexType name="affilationType">
        <xs:sequence>
            <xs:element name="category" type="boundedString"></xs:element>
            <xs:element name="description" type="boundedString"></xs:element>
        </xs:sequence>
        <xs:attribute name="typeId" type="xs:int" use="required"></xs:attribute>
    </xs:complexType>

    <!-- Funeral affilation -->
    <xs:complexType name="funeralAffilation">
        <xs:sequence>
            <xs:element name="name" type="boundedString"></xs:element>
            <xs:element ref="provider"></xs:element>
            <xs:element ref="affilationType"></xs:element>
            <xs:element name="unit" type="boundedString"></xs:element>
            <xs:element name="price" type="price"></xs:element>
            <xs:element name="inStorage" type="xs:int"></xs:element>
            <xs:element name="expected" type="xs:int"></xs:element>
            <xs:element name="suppliesStopped" type="xs:boolean"></xs:element>
            <xs:element name="photoUrl" type="boundedString"></xs:element>
            <xs:element name="description" type="boundedString"></xs:element>
        </xs:sequence>
        <xs:attribute name="affilationId" type="xs:int" use="required"></xs:attribute>
    </xs:complexType>

    <!-- Ordered affilation -->
    <xs:complexType name="orderedAffilation">
        <xs:sequence>
            <xs:element ref="funeralAffilation"></xs:element>
            <xs:element name="price" type="price"></xs:element>
            <xs:element name="affilationCount" type="positiveCount"></xs:element>
            <xs:element name="percentDiscount" type="percentDiscount"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Ordered affilations -->
    <xs:complexType name="orderedAffilations">
        <xs:sequence>
            <xs:element ref="orderedAffilation" minOccurs="0" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Service -->
    <xs:complexType name="service">
        <xs:sequence>
            <xs:element name="name" type="boundedString"></xs:element>
            <xs:element name="description" type="boundedString"></xs:element>
            <xs:element name="price" type="price"></xs:element>
        </xs:sequence>
        <xs:attribute name="serviceId" type="xs:int" use="required"></xs:attribute>
    </xs:complexType>

    <!-- Ordered service -->
    <xs:complexType name="orderedService">
        <xs:sequence>
            <xs:element ref="service"></xs:element>
            <xs:element name="price" type="price"></xs:element>
            <xs:element name="percentDiscount" type="percentDiscount"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Ordered services -->
    <xs:complexType name="orderedServices">
        <xs:sequence>
            <xs:element ref="orderedService" minOccurs="0" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Order -->
    <xs:complexType name="order">
        <xs:sequence>
            <xs:element ref="client"></xs:element>
            <xs:element name="registrationDate" type="xs:date"></xs:element>
            <xs:element name="appointmentDate" type="xs:date"></xs:element>
            <xs:element name="executionDate" type="xs:date"></xs:element>
            <!-- employees -->
            <xs:element ref="employeesInOrder"></xs:element>
            <!-- services -->
            <xs:element ref="orderedServices"></xs:element>
            <!-- affilations -->
            <xs:element ref="orderedAffilations"></xs:element>
        </xs:sequence>
        <xs:attribute name="orderId" type="xs:int" use="required"></xs:attribute>
    </xs:complexType>

    <!-- Orders -->
    <xs:complexType name="orders">
        <xs:sequence>
            <xs:element ref="order" minOccurs="0" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Funeral service -->
    <xs:complexType name="funeralService">
        <xs:sequence>
            <xs:element ref="orders" minOccurs="0" maxOccurs="1"></xs:element>
        </xs:sequence>
    </xs:complexType>


    <!-- ELEMENTS -->
    <!-- Client -->
    <xs:element name="client" type="client" />

    <!-- Employee -->
    <xs:element name="employee" type="employee" />

    <!-- Employee in order -->
    <xs:element name="employeeInOrder" type="employeeInOrder" />

    <!-- employeesInOrder -->
    <xs:element name="employeesInOrder" type="employeesInOrder" />

    <!-- Provider -->
    <xs:element name="provider" type="provider" />

    <!-- Affilation type -->
    <xs:element name="affilationType" type="affilationType" />

    <!-- Funeral affilation -->
    <xs:element name="funeralAffilation" type="funeralAffilation" />

    <!-- Ordered affilation -->
    <xs:element name="orderedAffilation" type="orderedAffilation" />

    <!-- Orderes affilations -->
    <xs:element name="orderedAffilations" type="orderedAffilations" />

    <!-- Service -->
    <xs:element name="service" type="service" />

    <!-- Ordered service -->
    <xs:element name="orderedService" type="orderedService" />

    <!-- Ordered services -->
    <xs:element name="orderedServices" type="orderedServices" />

    <!-- Order -->
    <xs:element name="order" type="order" />

    <!-- Orders -->
    <xs:element name="orders" type="orders" />

    <!-- Funeral service (root element) -->
    <xs:element name="funeralService" type="funeralService" />
</xs:schema>

=== EvseevDA/funeral-service-jaxb-demo/dataBase.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="dataBase.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<funeralService xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="dataBase.xsd">

    <orders>
        <order orderId="0">
            <client clientId="0">
                <surname>Пушкин</surname>
                <name>Александр</name>
                <patronymic>Александрович</patronymic>
                <country>Россия</country>
                <region>Нижегородская</region>
                <city>Нижний Новгород</city>
                <phoneNumber>+7-(920)-253-44-23</phoneNumber>
                <index>603155</index>
            </client>
            <registrationDate>2020-07-08</registrationDate>
            <appointmentDate>2020-07-23</appointmentDate>
            <executionDate>2020-07-23</executionDate>
            <employeesInOrder>
                <employeeInOrder>
                    <employee employeeId="0">
                        <surname>Сергеев</surname>
                        <name>Сергей</name>
                        <patronymic>Сергеевич</patronymic>
                        <jobTitle>Ритуальный агент</jobTitle>
                        <birthday>1999-06-23</birthday>
                        <hireDate>2020-05-05</hireDate>
                        <country>Россия</country>
                        <region>Нижегородская</region>
                        <city>Нижний Новгород</city>
                        <district>Нижегородский</district>
                        <street>Карла Маркса</street>
                        <houseNumber>64А</houseNumber>
                        <apartamentNumber>105</apartamentNumber>
                        <phoneNumber>+7-(999)-340-53-98</phoneNumber>
                        <photoUrl></photoUrl>
                        <note>Молодец</note>
                        <reportsTo>Вита Скалетта</reportsTo>
                    </employee>
                </employeeInOrder>
                <employeeInOrder>
                    <employee employeeId="1">
                        <surname>Александров</surname>
                        <name>Александр</name>
                        <patronymic>Александрович</patronymic>
                        <jobTitle>Водитель</jobTitle>
                        <birthday>2000-05-14</birthday>
                        <hireDate>2020-05-14</hireDate>
                        <country>Россия</country>
                        <region>Нижегородская</region>
                        <city>Нижний Новгород</city>
                        <district>Нижегородская</district>
                        <street>Долгополова</street>
                        <houseNumber>101</houseNumber>
                        <apartamentNumber>125</apartamentNumber>
                        <phoneNumber>+7-(930)-543-03-23</phoneNumber>
                        <photoUrl></photoUrl>
                        <note>Молодец</note>
                        <reportsTo>Вита Скалетта</reportsTo>
                    </employee>
                </employeeInOrder>
                <employeeInOrder>
                    <employee employeeId="2">
                        <surname>Федоров</surname>
                        <name>Федор</name>
                        <patronymic>Федорович</patronymic>
                        <jobTitle>Сотрудник сопроводительной бригады</jobTitle>
                        <birthday>2002-03-25</birthday>
                        <hireDate>2020-05-21</hireDate>
                        <country>Россия</country>
                        <region>Нижегородская</region>
                        <city>Нижний Новгород</city>
                        <district>Нижегородская</district>
                        <street>Фруктовая</street>
                        <houseNumber>87</houseNumber>
                        <apartamentNumber>89</apartamentNumber>
                        <phoneNumber>+7-(943)-786-55-12</phoneNumber>
                        <photoUrl></photoUrl>
                        <note>Молодец</note>
                        <reportsTo>Вита Скалетта</reportsTo>
                    </employee>
                </employeeInOrder>
                <employeeInOrder>
                    <employee employeeId="3">
                        <surname>Барбара</surname>
                        <name>Джо</name>
                        <patronymic></patronymic>
                        <jobTitle>Сотрудник сопроводительной бригады</jobTitle>
                        <birthday>1980-07-30</birthday>
                        <hireDate>2020-05-28</hireDate>
                        <country>Россия</country>
                        <region>Нижегородская</region>
                        <city>Нижний Новгород</city>
                        <district>Нижегородская</district>
                        <street>Лопатина</street>
                        <houseNumber>90</houseNumber>
                        <apartamentNumber>23</apartamentNumber>
                        <phoneNumber>+7-(920)-141-89-02</phoneNumber>
                        <photoUrl></photoUrl>
                        <note>Молодец</note>
                        <reportsTo>Вита Скалетта</reportsTo>
                    </employee>
                </employeeInOrder>
            </employeesInOrder>
            <orderedServices>
                <orderedService>
                    <service serviceId="0">
                        <name>Катафалк</name>
                        <description>Рассчитан на 10 гостией</description>
                        <price>4490.90</price>
                    </service>
                    <price>4490.90</price>
                    <percentDiscount>0</percentDiscount>
                </orderedService>
                <orderedService>
                    <service serviceId="1">
                        <name>Бальзамирование</name>
                        <description></description>
                        <price>3490.90</price>
                    </service>
                    <price>3490.90</price>
                    <percentDiscount>0</percentDiscount>
                </orderedService>
            </orderedServices>
            <orderedAffilations>
                <orderedAffilation>
                    <funeralAffilation affilationId="0">
                        <name>Гроб Г3 Деревянный</name>
                        <provider providerId="0">
                            <name>ИП Джаник Абдыбеков</name>
                            <speakTo>Джаник Абдыбеков</speakTo>
                            <jobTitle>Владелец и основатель</jobTitle>
                            <country>Россия</country>
                            <region>Московская</region>
                            <city>Москва</city>
                            <index>101103</index>
                            <phoneNumber>+7-(800)-900-40-40</phoneNumber>
                        </provider>
                        <affilationType typeId="0">
                            <category>Гроб</category>
                            <description></description>
                        </affilationType>
                        <unit>шт.</unit>
                        <price>7990.90</price>
                        <inStorage>10</inStorage>
                        <expected>5</expected>
                        <suppliesStopped>false</suppliesStopped>
                        <photoUrl></photoUrl>
                        <description></description>
                    </funeralAffilation>
                    <price>7990.90</price>
                    <affilationCount>1</affilationCount>
                    <percentDiscount>0</percentDiscount>
                </orderedAffilation>
                <orderedAffilation>
                    <funeralAffilation affilationId="1">
                        <name>Венок В1 "Арбуз"</name>
                        <provider providerId="1">
                            <name>ИП Лео Галанте</name>
                            <speakTo>Лео Галанте</speakTo>
                            <jobTitle>Владелец и основатель</jobTitle>
                            <country>Италия</country>
                            <region>Сицилийская</region>
                            <city>Сицилия</city>
                            <index>9338-12</index>
                            <phoneNumber>+7-(800)-999-09-90</phoneNumber>
                        </provider>
                        <affilationType typeId="1">
                            <category>Венок</category>
                            <description></description>
                        </affilationType>
                        <unit>шт.</unit>
                        <price>2990.90</price>
                        <inStorage>13</inStorage>
                        <expected>7</expected>
                        <suppliesStopped>false</suppliesStopped>
                        <photoUrl></photoUrl>
                        <description></description>
                    </funeralAffilation>
                    <price>2990.90</price>
                    <affilationCount>1</affilationCount>
                    <percentDiscount>0</percentDiscount>
                </orderedAffilation>
            </orderedAffilations>
        </order>

        <order orderId="1">
            <client clientId="1">
                <surname>Толстой</surname>
                <name>Лев</name>
                <patronymic>Николаевич</patronymic>
                <country>Россия</country>
                <region>Нижегородская</region>
                <city>Нижний Новгород</city>
                <phoneNumber>+7-(920)-253-44-23</phoneNumber>
                <index>603155</index>
            </client>
            <registrationDate>2020-07-08</registrationDate>
            <appointmentDate>2020-07-23</appointmentDate>
            <executionDate>2020-07-23</executionDate>
            <employeesInOrder>
                <employeeInOrder>
